# Generated by Django 4.1.5 on 2023-02-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ngo',
        ),
    ]
