# Generated by Django 4.1.5 on 2023-02-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_phil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ngo',
        ),
        migrations.DeleteModel(
            name='phil',
        ),
    ]
