# Generated by Django 4.1.5 on 2023-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mission', models.CharField(max_length=500)),
                ('history', models.CharField(max_length=500)),
                ('impact', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
