# Generated by Django 4.1.5 on 2023-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=150)),
                ('number', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
